<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - VeriBits</title>
    <link rel="stylesheet" href="/assets/css/main.css">
</head>
<body>
    <nav>
        <div class="container">
            <a href="/" class="logo">VeriBits</a>
            <ul>
                <li><a href="/tools.php">Tools</a></li>
                <li><a href="/cli.php">CLI</a></li>
                <li><a href="/pricing.php">Pricing</a></li>
                <li><a href="/about.php">About</a></li>
                <li><a href="/login.php">Login</a></li>
                <li><a href="/signup.php" class="btn btn-primary">Sign Up</a></li>
            </ul>
        </div>
    </nav>

    <section style="padding: 8rem 2rem 4rem;">
        <div class="container" style="max-width: 900px;">
            <h1 style="font-size: 3rem; margin-bottom: 1rem; text-align: center;">Terms of Service</h1>
            <p style="text-align: center; color: var(--text-secondary); margin-bottom: 3rem;">
                Last Updated: January 25, 2025
            </p>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">1. Acceptance of Terms</h2>
                <p style="margin-bottom: 1rem;">By accessing and using VeriBits (veribits.com, www.veribits.com, api.veribits.com), you accept and agree to be bound by the terms and conditions of this agreement. If you do not agree to these terms, please do not use our services.</p>
                <p>VeriBits is operated by After Dark Systems, LLC ("we," "us," or "our"). These terms govern your use of our file verification, cryptographic validation, and security analysis tools and services.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">2. Service Description</h2>
                <p style="margin-bottom: 1rem;">VeriBits provides professional-grade verification and validation tools including but not limited to:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li>File magic number detection and type identification</li>
                    <li>Digital signature verification (PGP, code signing certificates)</li>
                    <li>Hash generation and validation (MD5, SHA-1, SHA-256, SHA-512)</li>
                    <li>Steganography detection and analysis</li>
                    <li>Cryptographic key validation</li>
                    <li>Network and DNS security analysis</li>
                    <li>Developer utilities (JWT decoding, regex testing, etc.)</li>
                    <li>Code signing services for testing purposes</li>
                </ul>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">3. API Access & Usage</h2>
                <p style="margin-bottom: 1rem;">Access to the VeriBits API (api.veribits.com) is provided under the following conditions:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li><strong>Authentication:</strong> API access requires a valid API key obtained through account registration</li>
                    <li><strong>Rate Limits:</strong> Usage is subject to rate limits based on your subscription tier</li>
                    <li><strong>Fair Use:</strong> You agree not to abuse or overload our API infrastructure</li>
                    <li><strong>Non-Transferable:</strong> API keys are non-transferable and must be kept confidential</li>
                    <li><strong>Monitoring:</strong> We reserve the right to monitor API usage for security and compliance purposes</li>
                </ul>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">4. License Grant</h2>
                <p style="margin-bottom: 1rem;">Subject to your compliance with these terms, we grant you a limited, non-exclusive, non-transferable, revocable license to:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li>Access and use the VeriBits web interface and tools</li>
                    <li>Access the API using valid credentials</li>
                    <li>Use the VeriBits CLI tools in accordance with documentation</li>
                    <li>Download and view reports generated by our services</li>
                </ul>
                <p style="margin-top: 1rem;">This license does not grant you any rights to resell, redistribute, or sublicense our services without explicit written permission.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">5. User Responsibilities & Acceptable Use</h2>
                <p style="margin-bottom: 1rem;">You agree to use VeriBits services only for lawful purposes and in accordance with these terms. You will not:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li>Upload or analyze files containing malware, viruses, or malicious code with intent to harm</li>
                    <li>Attempt to circumvent security measures or rate limiting</li>
                    <li>Engage in any activity that disrupts or interferes with our services</li>
                    <li>Use our services to violate any applicable laws or regulations</li>
                    <li>Share your account credentials or API keys with unauthorized third parties</li>
                    <li>Reverse engineer, decompile, or attempt to extract source code from our services</li>
                    <li>Use automated systems (bots, scrapers) except through our official API</li>
                </ul>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">6. File Uploads & Data Processing</h2>
                <p style="margin-bottom: 1rem;"><strong>File Storage:</strong> Files uploaded for analysis are temporarily stored for processing and are automatically deleted within 24 hours. We do not retain files beyond what is necessary for service delivery.</p>
                <p style="margin-bottom: 1rem;"><strong>File Limits:</strong> File size limits are enforced based on your subscription tier. Exceeding these limits may result in processing failures or service interruptions.</p>
                <p style="margin-bottom: 1rem;"><strong>Prohibited Content:</strong> You may not upload files containing illegal content, child exploitation material, or content that violates intellectual property rights.</p>
                <p><strong>Your Responsibility:</strong> You are solely responsible for the content of files you upload and analyze using our services.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">7. Code Signing Services</h2>
                <p style="margin-bottom: 1rem;">VeriBits offers code signing services for testing and development purposes:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li><strong>Test Certificates Only:</strong> Code signing uses test certificates for development and evaluation purposes</li>
                    <li><strong>Not for Production:</strong> Code signed with VeriBits test certificates should not be used in production environments</li>
                    <li><strong>No Warranty:</strong> We provide no warranty regarding the validity or acceptance of signed code</li>
                    <li><strong>Usage Limits:</strong> Code signing is subject to monthly limits based on your subscription</li>
                </ul>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">8. Subscription & Billing</h2>
                <p style="margin-bottom: 1rem;"><strong>Free Trial:</strong> New users receive 5 free scans within a 30-day window. No credit card required.</p>
                <p style="margin-bottom: 1rem;"><strong>Paid Plans:</strong> Subscription fees are charged according to your selected plan (Monthly, Annual, or Enterprise). All fees are non-refundable except as required by law or as specified in our 30-day money-back guarantee.</p>
                <p style="margin-bottom: 1rem;"><strong>Auto-Renewal:</strong> Subscriptions automatically renew unless cancelled before the renewal date.</p>
                <p style="margin-bottom: 1rem;"><strong>Price Changes:</strong> We reserve the right to modify pricing with 30 days' notice to existing subscribers.</p>
                <p><strong>Payment Processing:</strong> Payments are processed through secure third-party payment processors. We do not store complete credit card information.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">9. Intellectual Property</h2>
                <p style="margin-bottom: 1rem;">All content, features, and functionality of VeriBits, including but not limited to text, graphics, logos, icons, images, audio clips, digital downloads, data compilations, and software, are the exclusive property of After Dark Systems, LLC and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property laws.</p>
                <p style="margin-bottom: 1rem;">The VeriBits name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of After Dark Systems, LLC. You may not use such marks without our prior written permission.</p>
                <p>You retain all rights to files and data you upload to our services. By uploading content, you grant us a limited license to process and analyze that content solely for the purpose of providing our services.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">10. Disclaimer of Warranties</h2>
                <p style="margin-bottom: 1rem;">VeriBits services are provided "AS IS" and "AS AVAILABLE" without warranties of any kind, either express or implied, including but not limited to:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li>Warranties of merchantability or fitness for a particular purpose</li>
                    <li>Warranties regarding accuracy, reliability, or completeness of results</li>
                    <li>Warranties that the service will be uninterrupted, secure, or error-free</li>
                    <li>Warranties that defects will be corrected</li>
                </ul>
                <p style="margin-top: 1rem;">You acknowledge that verification results are provided for informational purposes and should not be solely relied upon for critical security decisions. Always use multiple verification methods and consult security professionals for critical systems.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">11. Limitation of Liability</h2>
                <p style="margin-bottom: 1rem;">To the fullest extent permitted by applicable law, After Dark Systems, LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:</p>
                <ul style="list-style: disc; margin-left: 2rem; color: var(--text-secondary); line-height: 1.8;">
                    <li>Your access to or use of (or inability to access or use) the services</li>
                    <li>Any conduct or content of any third party on the services</li>
                    <li>Unauthorized access, use, or alteration of your transmissions or content</li>
                    <li>Errors or inaccuracies in verification results</li>
                    <li>Service interruptions or data loss</li>
                </ul>
                <p style="margin-top: 1rem;">Our total liability to you for any claim arising from your use of the services shall not exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">12. Indemnification</h2>
                <p>You agree to indemnify, defend, and hold harmless After Dark Systems, LLC, its officers, directors, employees, agents, and affiliates from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees and costs, arising out of or in any way connected with your access to or use of the services, your violation of these terms, or your violation of any third-party rights.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">13. Service Modifications & Termination</h2>
                <p style="margin-bottom: 1rem;"><strong>Modifications:</strong> We reserve the right to modify, suspend, or discontinue any part of our services at any time without notice.</p>
                <p style="margin-bottom: 1rem;"><strong>Termination by You:</strong> You may terminate your account at any time through your account settings.</p>
                <p style="margin-bottom: 1rem;"><strong>Termination by Us:</strong> We may terminate or suspend your access immediately, without prior notice, for any reason, including but not limited to violation of these terms.</p>
                <p><strong>Effect of Termination:</strong> Upon termination, your right to use the services will immediately cease. We may delete your data in accordance with our data retention policies.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">14. Third-Party Services & Links</h2>
                <p style="margin-bottom: 1rem;">VeriBits may contain links to third-party websites or services that are not owned or controlled by After Dark Systems, LLC. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.</p>
                <p>We strongly advise you to read the terms and conditions and privacy policies of any third-party services you visit.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">15. Export Compliance</h2>
                <p>You agree to comply with all applicable export and import laws and regulations. You represent that you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country, and that you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">16. Governing Law & Dispute Resolution</h2>
                <p style="margin-bottom: 1rem;">These terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.</p>
                <p style="margin-bottom: 1rem;">Any dispute arising from these terms or your use of the services shall first be attempted to be resolved through good faith negotiations. If negotiations fail, disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.</p>
                <p>You waive any right to participate in a class action lawsuit or class-wide arbitration.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">17. Changes to Terms</h2>
                <p style="margin-bottom: 1rem;">We reserve the right to modify these terms at any time. We will notify users of material changes via email or prominent notice on our website at least 30 days before the changes take effect.</p>
                <p>Your continued use of the services after changes become effective constitutes acceptance of the revised terms. If you do not agree to the changes, you must discontinue use of the services.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">18. Severability</h2>
                <p>If any provision of these terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these terms will otherwise remain in full force and effect.</p>
            </div>

            <div class="feature-card" style="margin-bottom: 2rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">19. Entire Agreement</h2>
                <p>These terms, together with our Privacy Policy and any other legal notices published by us on the services, constitute the entire agreement between you and After Dark Systems, LLC regarding the services and supersede all prior agreements and understandings.</p>
            </div>

            <div class="feature-card">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;">20. Contact Information</h2>
                <p style="margin-bottom: 1rem;">If you have any questions about these Terms of Service, please contact us:</p>
                <ul style="list-style: none; color: var(--text-secondary); line-height: 2;">
                    <li><strong>Email:</strong> <a href="mailto:legal@veribits.com" style="color: var(--accent-color);">legal@veribits.com</a></li>
                    <li><strong>Support:</strong> <a href="/support.php" style="color: var(--accent-color);">support.veribits.com</a></li>
                    <li><strong>Address:</strong> After Dark Systems, LLC</li>
                </ul>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2025 VeriBits. All rights reserved.</p>
            <p style="margin-top: 0.5rem;">
                A service from <a href="https://www.afterdarksys.com/" target="_blank" rel="noopener">After Dark Systems, LLC</a>
            </p>
            <p style="margin-top: 1rem;">
                <a href="/privacy.php" style="color: var(--text-secondary); margin: 0 1rem;">Privacy</a>
                <a href="/terms.php" style="color: var(--text-secondary); margin: 0 1rem;">Terms</a>
                <a href="/support.php" style="color: var(--text-secondary); margin: 0 1rem;">Support</a>
            </p>
        </div>
    </footer>

    <script src="/assets/js/main.js"></script>
</body>
</html>
